### ISSUE TITLE
Redirect error

### ISSUE THREAD

**Issue by galcivar** [greguz/node-sails-hook-httpsredirect#1]
Hi, I get the following error that makes my server crash:

```
/home/ubuntu/server/node_modules/sails-hook-httpsredirect/index.js:88
          var location = 'https://' + req.headers.host.replace(/:.+/, '')
                                                      ^

TypeError: Cannot read property 'replace' of undefined
    at Server.<anonymous> (/home/ubuntu/server/node_modules/sails-hook-httpsredirect/index.js:88:55)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:528:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
```

**Comment by greguz** [comment]
This package is being deprecated.
